### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by tatsumiwa-pg** [tatsumiwa-pg/protospace-36864#1]
# URL
[protospace-36864のページ（本番環境）へ](https://protospace-36864.herokuapp.com/)

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by tatsumiwa-pg** [comment]
ありがとうございます！
気合入れて頑張ります！
